### ISSUE TITLE
Bug: InterVar call with P with PVS1=1, downgrade to LP after autoPVS1 adjustment

### ISSUE THREAD

**Issue by jungkim2** [diskin-lab-chop/AutoGVP#100]
#### Provide the command used or report the bug here

For variants that doesn't have ClinVar and taking InterVar call, InterVar is calling Pathogenic, but gets downgraded to Likely_pathogenic in final_call. 

Here are some example coordinates

16-3254166-G-T
16-3247248-T-G

#### Add Session info
Run `sessionInfo()` and post the output below

**Comment by rjcorb** [comment]
@jungkim2 are these variants in any of the test files? I don't seem them.

**Comment by jungkim2** [comment]
they are not in the test file. I gave those specific example files to @naqvia

**Comment by naqvia** [comment]
So for the `16-3247248-T-G` it is getting a LP call due to this check in the code: 
```
     ifelse((evidencePVS1 == 1 & evidencePM == 1) |
        (evidencePS == 1 & evidencePM >= 1) |
        (evidencePS == 1 & evidencePP >= 2) |
        (evidencePM >= 3) |
        (evidencePM == 2 & evidencePP >= 2) |
        (evidencePM == 1 & evidencePP >= 4), "Likely_pathogenic",
```
this is because PVS1=1, PM= 1 and PP=1 from the intervar line:
`PVS1=1 PS=[0, 0, 0, 0, 0] PM=[0, 1, 0, 0, 0, 0, 0] PP=[0, 0, 1, 0, 0, 0] BA1=0 BS=[0, 0, 0, 0, 0] BP=[0, 0, 0, 0, 0, 0, 0, 0] `

This logic is documented in the readme under the `Likely pathogenic` heading. Can you please comment @jungkim2 and clarify? cc @jharenza

**Comment by jungkim2** [comment]
yes, one of them indeed is LP! But other one should be P.
