### ISSUE TITLE
Bug:0 stars getting wrong classification

### ISSUE THREAD

**Issue by jungkim2** [diskin-lab-chop/AutoGVP#111]
#### Provide the command used or report the bug here

1-149784224-C-T
This variant has final_call pathogenic when criterion is na. 
InterVar: Pathogenic PVS1=1 PS=[0, 0, 0, 0, 0] PM=[0, 0, 0, 0, 0, 0, 0] PP=[0, 0, 1, 0, 1, 0] BA1=0 BS=[0, 0, 0, 0, 0] BP=[0, 0, 0, 0, 0, 0, 0, 0]

With criterion na, final InterVar should be PP=2. Evidence compile output also shows that PVS1 = 1 for this particular variant (other variants that have criterion na doesn't have this issue)

7-152248171-G-A
This variant has final_call pathogenic, when the original InterVar says VUS.
InterVar: Uncertain significance PVS1=1 PS=[0, 0, 0, 0, 0] PM=[0, 0, 0, 0, 0, 0, 0] PP=[0, 0, 1, 0, 0, 0] BA1=0 BS=[1, 0, 0, 0, 0] BP=[0, 0, 0, 0, 0, 0, 0, 0]
Evidence compile output has correct information.  

In both case, ClinVar 0 star with Pathogenic classification

#### Add Session info
Run `sessionInfo()` and post the output below

**Comment by jungkim2** [comment]
output file of those two variants
[issue111_output.txt](https://github.com/diskin-lab-chop/AutoGVP/files/12255320/issue111_output.txt)

**Comment by naqvia** [comment]
What do you mean by `Evidence compile output` has correct information?

For first variant The PP intervar info is` PP=[0, 0, 1, 0, 1, 0]`, so its 2 like you said, but I am ignoring PP5, so it being called as `PP=1`.   I thought we had decided to remove PP5? Can you clarify? 

And for second variant it should be PVS1=1, PP = 1 and BS=1 , correct? So the second variant is getting `Pathogenic` call due to this statement:
```
 final_call = ifelse((evidencePVS1 == 1 &
      ((evidencePS >= 1) |
        (evidencePM >= 2) |
        (evidencePM == 1 & evidencePP == 1) |
        (evidencePP >= 2))), "Pathogenic",
```
bc` PVS1=1` and `PM =1` and `PP=1` ... so thats why its getting `Pathogenic` call. Why is this wrong?

**Comment by jungkim2** [comment]
sorry. You are right. We are excluding PP5. So that first one should have PP1 and BS1. Since that variant has autoPVS1 na (which means unmet). Without PVS1, it should get VUS.  

For second one it has PVS1=1, PP=1, BS=1. PVS1=1 and PP=1 doesn't apply to that logic. BS is different from PS

**Comment by jungkim2** [comment]
Issue resolved
