### ISSUE TITLE
Bug: Variants with resolved ClinVar calls are reporting Intervar call in final output

### ISSUE THREAD

**Issue by rjcorb** [diskin-lab-chop/AutoGVP#122]
#### Provide the command used or report the bug here

There are variant with conflicting ClinVar interpretations that are resolved by analyzing submissions, but in final output the Intervar call is taken despite ClinVar being listed as reasoning. For example: 

chr | start | ref | alt | rs_id | gene_symbol_vep | variant_classification_vep | HGVSg | HGVSc | HGVSp | autogvp_call | autogvp_call_reason | clinvar_stars | clinvar_clinsig | intervar_evidence | gnomad_3_1_1_AF_non_cancer
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
chr17 | 7675189 | G | C | rs1057519977 | TP53 | missense_variant | chr17:g.7675189G>C | c.423C>G | p.Cys141Trp | Uncertain_significance | ClinVar | 1NR | Likely pathogenic | InterVar: Uncertain significance PVS1=0 PS=[0, 0, 0, 0, 0] PM=[1, 1, 0, 0, 0, 0, 0] PP=[0, 0, 1, 0, 0, 0] BA1=0 BS=[0, 0, 0, 0, 0] BP=[0, 0, 0, 0, 0, 0, 0, 0] | 0

#### What version are you using?

Latest release

#### Add Session info
Run `sessionInfo()` and post the output below

**Comment by naqvia** [comment]
Good catch. 1NRs shouldn't be going into the intervar re-calculation steps, so it could just be we not filtering it since they are labeled correctly. I think id like to merge the latest PRs, and see if this issue persists before tackling this bc there a lot of nuanced changes and the test data should pick this up as well.
