### ISSUE TITLE
Add auto gene liftover for `PVS1.level` of autoPVS1

### ISSUE THREAD

**Issue by jharenza** [diskin-lab-chop/AutoGVP#23]
AutoPVS1 uses VEP104 by default. 

Using the custom input workflow, users run AutoPVS1 on their own.

Users may annotate their germline file with any VEP version. We need that VEP's gene symbols to match those of the `PVS1.level` file in AutoPVS1.

Idea (open to suggestions):
- Add a preprocessing script in a new folder to allow users to run [this gene symbol liftover code](https://github.com/d3b-center/D3b-DGD-Collaboration/blob/main/scripts/update_gene_symbols.py) on the PVS1.level file [here](https://github.com/diskin-lab-chop/pathogenicity-assessment/blob/main/autopvs1/data/PVS1.level), which users can run prior to their running of AutoPVS1. This result file can be put into their scratch or other directory so they can grab and replace it in their AutoPVS1 instance. This seems to be like a jenky workaround. I would almost rather us run AutoPVS1 for them with an option of the VEP version being input. If 104, do no liftover. If other, do the liftover. Open to suggestions @sakshamphul @jungkim2 @naqvia

**Comment by migbro** [comment]
The issue with that is that you kind of have to find the right tsv: https://ftp.ebi.ac.uk/pub/databases/genenames/hgnc/archive/monthly/tsv/ that coincides with the VEP release by date. If we're lucky, maybe buried inside there is when they used the HGNC symbols. Using the latest might not be enough because you want to ensure that the symbols that were used for annotation pop up in that file, so if they changed again later, you don't actually want to capture that.

**Comment by jharenza** [comment]
completed with #26
